# Generated by Django 2.2 on 2023-08-17 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Comunidades',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre del departamento', max_length=100, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Departamento')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'ordering': ['descripcion'],
                'unique_together': {('departamento', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Poblacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Poblaciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre del proyecto', max_length=100, unique=True)),
                ('contacto', models.CharField(help_text='Nombre del contacnto en territorio', max_length=100)),
                ('telefono', models.CharField(help_text='Telefono', max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('donante', models.CharField(blank=True, help_text='Ente donante', max_length=250, null=True)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('ejecucion', models.CharField(choices=[('DIRECTA', 'DIRECTA'), ('SOCIO', 'SOCIO')], default='DIRECTA', max_length=7)),
                ('nombre_socio', models.CharField(blank=True, help_text='Nombre del socio', max_length=250, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pueblo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=100, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pueblos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Nombre del programa', max_length=100)),
                ('objetivo', models.CharField(help_text='Objetivo', max_length=900)),
                ('cantidad_beneficiados', models.IntegerField()),
                ('montoPND1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND1', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND1', models.CharField(blank=True, max_length=500, null=True)),
                ('montoPND2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND2', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND2', models.CharField(blank=True, max_length=500, null=True)),
                ('montoPND3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND3', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND3', models.CharField(blank=True, max_length=500, null=True)),
                ('montoPND4', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND4', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND4', models.CharField(blank=True, max_length=500, null=True)),
                ('montoPND5', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND5', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND5', models.CharField(blank=True, max_length=500, null=True)),
                ('montoPND6', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND6', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND6', models.CharField(blank=True, max_length=500, null=True)),
                ('montoPND7', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND7', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND7', models.CharField(blank=True, max_length=500, null=True)),
                ('montoPND8', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND8', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND8', models.CharField(blank=True, max_length=500, null=True)),
                ('montoPND9', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND9', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND9', models.CharField(blank=True, max_length=500, null=True)),
                ('montoPND10', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaPND10', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorPND10', models.CharField(blank=True, max_length=500, null=True)),
                ('PNDOtro1', models.CharField(blank=True, max_length=500, null=True)),
                ('montoOtro1', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaOtro1', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorOtro1', models.CharField(blank=True, max_length=500, null=True)),
                ('PNDOtro2', models.CharField(blank=True, max_length=500, null=True)),
                ('montoOtro2', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaOtro2', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorOtro2', models.CharField(blank=True, max_length=500, null=True)),
                ('PNDOtro3', models.CharField(blank=True, max_length=500, null=True)),
                ('montoOtro3', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('metaOtro3', models.CharField(blank=True, max_length=500, null=True)),
                ('indicadorOtro3', models.CharField(blank=True, max_length=500, null=True)),
                ('comunidad', models.ManyToManyField(to='inv.Comunidad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Municipio')),
                ('poblacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Poblacion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Proyecto')),
                ('pueblo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Pueblo')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detalle Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Pnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Prioridad Nacional de Desarrollo', max_length=100, unique=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prioridades ',
            },
        ),
        migrations.AddField(
            model_name='comunidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Municipio'),
        ),
        migrations.AddField(
            model_name='comunidad',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='comunidad',
            unique_together={('municipio', 'descripcion')},
        ),
    ]
